export const ARTICLES_JAVA = [
    {
        id:0,
        contentid: 0,
        content:"An implicit super() call is included in each constructor which does not include either this() or an explicit super() call as its first statement. The super() statement is used to invoke a constructor of the superclass.The implicit super() can be replaced by an explicit super(). The super statement must be the first statement of the constructor. The explicit super allows parameter values to be passed to the constructor of its superclass and must have matching parameter types. A super() call in the constructor of a subclass will result in the call of the relevant constructor from the superclass, based on the signature of the call. This is called constructor chaining.super() or this() construct: If used in the constructor, it must occur as the first statement in a constructor, and it can only be used in a constructor declaration. This implies that this() and super() calls cannot both occur in the same constructor. Just as the this() construct leads to the chaining of constructors in the same class, the super() construct leads to the chaining of subclass constructors to superclass constructors. If a constructor has neither a this() nor a super() construct as its first statement, then a super() call to the default constructor in the superclass is inserted implicitly."
    },
    {
        id:1,
        contentid:1,
        content:"The Java language has experienced various modifications since JDK 1.0 as well as numerous inclusions of courses and units to the standard library. Since J2SE 1.4, the development of the Java language has been overseen by the Java Community Process (JCP), which utilizes Java Specification Requests (JSRs) to propose and designate extensions and modifications to the Java program. The language is stipulated by the Java Language Specification (JLS); changes to the JLS are conducted under JSR 901.In addition to the language variations, much more exciting changes have been made to the Java Class Library over time, which has grown from a few hundred classes in JDK 1.0 to over three thousand in J2SE 5. Entire new APIs, such as Swing and Java2D, have been proposed, and many of the original JDK 1.0 classes and practices have been opposed. Some programs allow translation of Java programs from one version of the Java platform to an antique one (for example Java 5.0 backported to 1.4).In September 2017, Mark Reinhold, Chief Designer of the Java Platform, aimed to change the release series to “one characteristic release every six months” preferably than the current two-year schedule, and later the plan took effect.Java 8 is the currently supported long-term-support (LTS) version, and Java 10 is the presently endorsed accelerated release version, as of March 20, 2018. Java 10 support ends on the same date that support for Java 11 begins, planned for September 2018, and Java 11 will be the next LTS after Java 8. Java 7 is no longer openly supported, Java 9 has stopped accepting updates since Java 9 was a short-term rapid release version that has been replaced by Java 10, and “end of public updates” for Java 8 is estimated for January 2019 for commercial use, and not earlier than December 2020 for non-commercial use."
    },
    {
        id:2,
        contentid: 2,
        content:"Java is a general, all-purpose computer programming language that is circumstantial, class-based, object-oriented, and specially designed to have few application dependencies as possible. Java was developed initially for interactive television, but it was too advanced technology for the digital cable television industry at the time. It is proposed to let application developers “write once, run anywhere, suggesting that compiled Java code can run on all platforms that condone Java without the necessity to recompile. Java applications are compiled to bytecode that can run on any Java virtual machine (JVM) regardless of computer architecture.Java is all-encompassing us, but that wasn’t the case; it had effortless starts. It all began in 1990 when Sun Microsystems engineer Patrick Naughton became more annoyed with the situation of Sun’s C++ and C APIs and was granted the chance to create an alternative language as part of The Stealth Project.The Stealth Project soon changed to the Green Project, with Mike Sheridan and James Gosling joining the ranks, and the group began developing new technology for programming next-generation smart appliances.A compiled code was unproductive for other processors, and it had to be recompiled. So the partners of 5 also called as Green Team started to work towards generating an accessible and cost-efficient resolution. They worked for 18 months in establishing a flexible, platform-independent language that could create a code which can run on the diversity of processors under different environments. The above necessity led to the creation of Java."
    }  
];